{
 "title": "HTTP Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "HTTP Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate (HTTP Server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (http_request_method, http_route) (\r\n  rate(otel_http_server_request_duration_seconds_count{http_route!=\"\"}[5m])\r\n)",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Latência P50/P95/P99 lado a lado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\r\n  histogram_quantile(\r\n    0.50,\r\n    sum by (le) (\r\n      rate(\r\n        otel_http_server_request_duration_seconds_bucket{\r\n          exported_job = \"order-service\",\r\n          http_route != \"\",\r\n          http_response_status_code !~ \"3..\"\r\n        }[5m]\r\n      )\r\n    )\r\n  ),\r\n  \"quantile\", \"50\", \"\", \"\"\r\n)\r\nor\r\nlabel_replace(\r\n  histogram_quantile(\r\n    0.95,\r\n    sum by (le) (\r\n      rate(\r\n        otel_http_server_request_duration_seconds_bucket{\r\n          exported_job = \"order-service\",\r\n          http_route != \"\",\r\n          http_response_status_code !~ \"3..\"\r\n        }[5m]\r\n      )\r\n    )\r\n  ),\r\n  \"quantile\", \"95\", \"\", \"\"\r\n)\r\nor\r\nlabel_replace(\r\n  histogram_quantile(\r\n    0.99,\r\n    sum by (le) (\r\n      rate(\r\n        otel_http_server_request_duration_seconds_bucket{\r\n          exported_job = \"order-service\",\r\n          http_route != \"\",\r\n          http_response_status_code !~ \"3..\"\r\n        }[5m]\r\n      )\r\n    )\r\n  ),\r\n  \"quantile\", \"99\", \"\", \"\"\r\n)",
     "legendFormat": "P{{quantile}}"
    }
   ]
  },
  {
   "title": "Latência P95 (HTTP Server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, http_request_method, http_route) (\r\n    rate(\r\n      otel_http_server_request_duration_seconds_bucket{\r\n        exported_job=\"order-service\",\r\n        http_route!=\"\",\r\n        http_response_status_code!~\"3..\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "P95 {{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(\r\n  otel_http_server_request_duration_seconds_count{\r\n      exported_job = \"order-service\",\r\n      http_response_status_code =~ \"5..\"\r\n  }[5m]\r\n)\r\n/\r\nrate(\r\n  otel_http_server_request_duration_seconds_count{\r\n    exported_job = \"order-service\"\r\n  }[5m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}